name: 'astraljaeger/bundle-action'
description: 'A GitHub Action to create zip release bundles'
author: 'Felix Hillebrand'

branding:
  icon: 'package'
  color: 'yellow'

inputs:
  bundleInclude:
    description: 'The path to your bundleinclude file'
    required: true
    default: '.bundleinclude'
  bundle:
    description: 'The path to your bundleinclude file'
    required: true
    default: './bundle'
  overrideExisting:
    description: 'Override exisiting bundles'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
