name: '@astraljaeger/bundle-action'
description: 'A GitHub Action to create zip release bundles'
author: 'Felix Hillebrand'

branding:
  icon: 'package'
  color: 'yellow'
inputs:
  bundleinclude: # id of input
    description: 'The path to your bundleinclude file'
    required: true
    default: '.bundleinclude'
  bundle: # id of input
    description: 'The path to your bundleinclude file'
    required: true
    default: './bundle'

  analytics:
    description: 'Enable analytics for our usage to improve the action'
outputs:

runs:
  using: 'node20'
  main: 'index.js'
